import { z } from 'zod';

export const TicketValidations = {
  create: z.object({
    _id: z.string(),
    eventId: z.string(),
    attendeeId: z.string(),
    ticketType: z.string(),
    price: z.number(),
    quantity: z.number(),
    totalAmount: z.number(),
    promotionCode: z.string().optional(),
    discountAmount: z.number(),
    finalAmount: z.number(),
    status: z.string(),
    paymentStatus: z.string(),
    qrCode: z.string(),
    ticketNumber: z.string(),
    checkedIn: z.boolean(),
    checkedInAt: z.string().datetime().optional(),
  }),

  update: z.object({
    _id: z.string().optional(),
    eventId: z.string().optional(),
    attendeeId: z.string().optional(),
    ticketType: z.string().optional(),
    price: z.number().optional(),
    quantity: z.number().optional(),
    totalAmount: z.number().optional(),
    promotionCode: z.string().optional(),
    discountAmount: z.number().optional(),
    finalAmount: z.number().optional(),
    status: z.string().optional(),
    paymentStatus: z.string().optional(),
    qrCode: z.string().optional(),
    ticketNumber: z.string().optional(),
    checkedIn: z.boolean().optional(),
    checkedInAt: z.string().datetime().optional(),
  }),
};
